<a href="https://colab.research.google.com/github/simratdhill0n/machinelearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
myarr = np.array([[44,565,434,534]], np.int64)

In [11]:
myarr

array([[ 44, 565, 434, 534]])

In [12]:
myarr.shape

(1, 4)

In [13]:
myarr.dtype

dtype('int64')

In [15]:
myarr[0,1]

565

In [16]:
myarr[0,1]=45

In [17]:
myarr[0,1]

45

**Array Creation Method in numpy**



1.   Conversion from other python structures.


In [20]:
 myarr = np.array([[44,565,434,534]], np.int64)

In [22]:
threedarray = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [23]:
threedarray

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])



2.   intrinctive objects



In [24]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
rng = np.arange(15)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
lspace = np.linspace(1,50,5)

In [30]:
lspace

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [31]:
emp = np.empty((4,6))

In [32]:
emp

array([[2.28715161e-316, 0.00000000e+000, 7.33730453e+223,
        1.42682308e+188, 5.87530072e+228, 4.35922639e+228],
       [4.35887763e+228, 9.53305350e-307, 5.56111653e+180,
        1.57789222e+214, 3.82835733e+045, 4.91375506e+252],
       [1.55078789e+223, 1.75074555e+190, 1.09431323e-309,
        5.22150394e-215, 2.17388522e-312, 2.41695321e-311],
       [1.68544454e+150, 3.76202686e+199, 5.35101054e+228,
        1.96186063e+189, 1.14905942e+170, 4.94065646e-324]])

In [33]:
emp_like = np.empty_like(lspace)

In [34]:
emp_like

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [35]:
ide = np.identity(5)

In [36]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
arr = np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr = arr.reshape(3,33)

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])